### PR TITLE
Address new JPL naming conventions

### LINKED ISSUE #559: IndexError: string index out of range in JPL desigination fetch
View details in Rollbar: [https://rollbar.com/LCO/NEOexchange/items/214/](https://rollbar.com/LCO/NEOexchange/items/214/)
I was able to trigger this on demand with:
```
In [33]: from core.views import update_MPC_orbit

In [34]: update_MPC_orbit('62391', origin='L')
[20/Jul/2021 17:02:18] INFO More recent elements already stored for 62391
INFO:core.views:More recent elements already stored for 62391
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-34-6f6407c4e7eb> in <module>
----> 1 update_MPC_orbit('62391', origin='L')

~/git/neoexchange/neoexchange/core/views.py in update_MPC_orbit(obj_id_or_page, dbg, origin, force)
   3019     # Update Physical Parameters
   3020     if body.characterization_target() or body.source_type == 'C':
-> 3021         update_jpl_phys_params(body)
   3022         if body.source_type == 'C':
   3023             # The MPC DB doesn't return any info for comets; update the Body's

~/git/neoexchange/neoexchange/core/views.py in update_jpl_phys_params(body)
   3070     try:
   3071         store_jpl_physparams(resp['phys_par'], body)
-> 3072         store_jpl_desigs(resp['object'], body)
   3073         store_jpl_sourcetypes(resp['object']['orbit_class']['code'], resp['object'], body)
   3074     except KeyError:

~/git/neoexchange/neoexchange/astrometrics/sources_subs.py in store_jpl_desigs(obj, body)
   2718 
   2719     # parsing through JPL designations
-> 2720     des_dict_list = parse_jpl_fullname(obj)
   2721 
   2722     des_alt = obj['des_alt']

~/git/neoexchange/neoexchange/astrometrics/sources_subs.py in parse_jpl_fullname(obj)
   2780             part1, part2, part3, part4 = fullname.split(' ')
   2781             number = part1
-> 2782             if part2[0].isalpha:
   2783                 name = part2
   2784         elif space_num == 2:

IndexError: string index out of range

```

### PR DESCRIPTION
**Pull request by jchate6**
closes #559 
silly JPL and their silly changes

### CODE REVIEW

**Comment by talister** [comment]
@jchate6 could you do a quick in `horizons_ephem` to see if it is similarly afflicted with undesired changes in name in the returned table?

**Comment by jchate6** [comment]
> @jchate6 could you do a quick in `horizons_ephem` to see if it is similarly afflicted with undesired changes in name in the returned table?

This specific issue cannot affect our Horizons call unless we tried to use an object's "full name" which would likely break anyway. 
`Horizons()` will take a name, number, provisional designation, or candidate designation and perform a search using that information. This change is (as far as I can tell) only applicable to the number of spaces in the "full name" for numbered asteroids with no alphabetic name.

**Comment by talister** [comment]
> > @jchate6 could you do a quick in `horizons_ephem` to see if it is similarly afflicted with undesired changes in name in the returned table?
> 
> This specific issue cannot affect our Horizons call unless we tried to use an object's "full name" which would likely break anyway.
> `Horizons()` will take a name, number, provisional designation, or candidate designation and perform a search using that information. This change is (as far as I can tell) only applicable to the number of spaces in the "full name" for numbered asteroids with no alphabetic name.

OK, I've got the wrong end of the damp string... The various plot functions in `obsgeomplot.py` all call `make_targetname()` on the first line of JPL results - could *that* `sanitize_object_name()` be broken with the same backend JPL change in naming ?

**Comment by jchate6** [comment]
Ah, looks like a maybe some day...
`sanitize_object_name()` is also anticipating a certain number of spaces.
However, the name currently returned in item 1 of a horizons table is still with the old number of spaces.
We can try to re-work `sanitize_object_name()` in anticipation of this change propagating itself through in the future, or we can wait until that happens.

**Comment by talister** [comment]
> > @jchate6 could you do a quick in `horizons_ephem` to see if it is similarly afflicted with undesired changes in name in the returned table?
> 
> This specific issue cannot affect our Horizons call unless we tried to use an object's "full name" which would likely break anyway.
> `Horizons()` will take a name, number, provisional designation, or candidate designation and perform a search using that information. This change is (as far as I can tell) only applicable to the number of spaces in the "full name" for numbered asteroids with no alphabetic name.

OK, I've got the wrong end of the damp string... The various plot functions in `obsgeomplot.py` all call `make_targetname()` on the first line of JPL results - could *that* `sanitize_object_name()` be broken with the same backend JPL change in naming ?

> Ah, looks like a maybe some day...
> `sanitize_object_name()` is also anticipating a certain number of spaces.
> However, the name currently returned in item 1 of a horizons table is still with the old number of spaces.
> We can try to re-work `sanitize_object_name()` in anticipation of this change propagating itself through in the future, or we can wait until that happens.

I think fix now since I think that name is also used for the plot filenames in the S3 bucket which are then used for checking on whether the plots are in date... Clearly we should have: https://xkcd.com/208/

**Review by talister — APPROVED** [review]

**Pull request merged**
