### PR TITLE
Feature/galactic coords

### PR DESCRIPTION
**Pull request by talister**
@zemogle this adds a Milky Way outline to the RA/Dec plot type on the 'Show Visibilities' page and creates a new Galactic longitude vs latitude plot type.
There is a general issue with the visibility plots in that often only some will load and a refresh is needed to get all load. This seems to happen both locally and when it's running in S3:
broken_plots_screenshot
The call to `astroquery.jpl.horizons` in `horizons_ephem()` should be pickled and cached automagically and then used for all the plot generations; I though it might be a permissions issue since this goes `~/.astropy/cache/astroquery/Horizons/` which could be problematic when running under nginx but:

- I *think* this is taken care of by making suitable directories in the `docker/init` but maybe something as changed
- if this was the case, then this wouldn't fail under a local `runserver` when in fact it does 

If you have any thoughts on what could be going wrong or ways to debug/profile what's going wrong in the template or elsewhere...

### CODE REVIEW

**Comment by zemogle** [comment]
After experimenting for most of the day, I think I know whats happening. I initially thought it was the html being faster to render than the plot generating code. However I think its the file writing and then re-reading. As a testI put a `time.sleep(1)` into `make_visibility_plot` and all the plots load fine.

I have a solution to this, using  `BytesIO` objects but before having a run at it, I wanted to make sure there wasn't another reason you wanted to write a file. 

In some cases JPL Horizons times out which is a separate issue.

**Comment by zemogle** [comment]
I may have been too hasty here. I've been doing some more experimentation and it looks like randomly Horizons does not generate ephemeris. There were untrapped exceptions which didn't help:

`ConnectionError != requests.exceptions.ConnectionError`

I think astroquery/Horizons is not able to cope with multiple calls so soon after each other. Some go through quickly, the others are deferred. The deferred ones return `False` but continue in the background and go into the `.astropy/astroquery/cache`, which is why a refresh makes them work. I'll look into this more tomorrow. I think we might be able to combine the calls.

**Comment by talister** [comment]
> I may have been too hasty here. I've been doing some more experimentation and it looks like randomly Horizons does not generate ephemeris. There were untrapped exceptions which didn't help:
> 
> `ConnectionError != requests.exceptions.ConnectionError`
> 
> I think astroquery/Horizons is not able to cope with multiple calls so soon after each other. Some go through quickly, the others are deferred. The deferred ones return `False` but continue in the background and go into the `.astropy/astroquery/cache`, which is why a refresh makes them work. I'll look into this more tomorrow. I think we might be able to combine the calls.

Urgh, I hate race conditions. The aim of the code was to reduce the load on JPL HORIZONS which is why we get 1 months of ephemeris and then write the generated plot file to S3 so we can use it as a cache via `plots.find_existing_vis_file()` and `plots.determine_plot_valid()` so we return the same once-generated plot for the next month (except for the uncertainty plot which needs to be updated daily)

**Comment by zemogle** [comment]
I've come up with a fix which delays loading the image sequence by 1s. Firing them all within mililseconds of each other was causing the issues. Let me know what you think.  I also fixed the Horizons timeout exception.

**Comment by talister** [comment]
> I've come up with a fix which delays loading the image sequence by 1s. Firing them all within mililseconds of each other was causing the issues. Let me know what you think. I also fixed the Horizons timeout exception.

Thanks @zemogle that's some good sleuthing. What are the tradeoffs between using the dummyimage.com service vs just hand-rolling static versions in GIMP/Photoshop and adding them to the `static/` ?

**Comment by zemogle** [comment]
We should definitely have our own static assets for this. The dummy images are just until we finalise this approach.

**Comment by talister** [comment]
> We should definitely have our own static assets for this. The dummy images are just until we finalise this approach.

OK, sounds good. I will put this branch up on AWS dev in place of the TFN support branch and see how it fares.

**Pull request merged**
