### PR TITLE
add timeout exception to horizons_ephem

### PR DESCRIPTION
**Pull request by jchate6**
closes issue #586 

I'm not sure this is sufficient.

### CODE REVIEW

**Comment by jchate6** [comment]
Should we make some tests for these with mocked bad connections of various kinds?

**Comment by talister** [comment]
> Should we make some tests for these with mocked bad connections of various kinds?

We should certainly try although it seems difficult to catch all the many and varied ways throughout the stack that seem to be able to fail... I did do a `Mock` for `fetchpage_and_make_soup` which could serve as a basis: 
https://github.com/LCOGT/neoexchange/pull/571/files#diff-9a6088052179befcdaec793fd794eb48f210e6b84ada797a74e552b4a978dd8b

**Comment by jchate6** [comment]
I'm having a lot of trouble reproducing the same errors seen in the rollbar stacktrace...

**Comment by talister** [comment]
> I'm having a lot of trouble reproducing the same errors seen in the rollbar stacktrace...

I think we're seeing a combination of wrapped exceptions from `urllib3`: https://urllib3.readthedocs.io/en/stable/reference/urllib3.exceptions.html#module-urllib3.exceptions but some of the low-level ones from `socket` are not being trapped. So I think we need to mock both. Not sure if there are libraries for testing this - seems common enough **someone** should have helped out in this regard..

**Review by talister — CHANGES_REQUESTED** [review]
I suggest you incorporate the "test for populated `Exception` attributes" I did in https://github.com/LCOGT/neoexchange/commit/aaef0477502b5352ce7367099503f51088b9440c as otherwise I see a new Rollbar error in our future...

**Comment by jchate6** [comment]
@talister does this accomplish basically the same thing?

**Comment by talister** [comment]
> @talister does this accomplish basically the same thing? Or is it important to specifically capture the case when those outputs are unexpected in that way?

Thought the `f`-format specifier wasn't happy with `None`s which is the issue (the returned `Exception` sometimes doesn't have those attributes)

**Comment by jchate6** [comment]
> > @talister does this accomplish basically the same thing? Or is it important to specifically capture the case when those outputs are unexpected in that way?
> 
> Thought the `f`-format specifier wasn't happy with `None`s which is the issue (the returned `Exception` sometimes doesn't have those attributes)

`f"{None}"` prints "None"

**Comment by jchate6** [comment]
that's one of the major benefits of `f`-format, it is type independent. #polymorphism

**Comment by talister** [comment]
> that's one of the major benefits of `f`-format, it is type independent. #polymorphism

That would work; we don't actually care about the types in this case

**Pull request merged**
